package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.communication.Communication;
import rs.ac.bg.fon.ps.PSCommon.domain.User;
/**
 * FOrma koja predstavlja prijavnu formu
 * Ukoliko korisnik upise dobro username i password
 * prelazi na sledecu formu u suprotnom ostaje na istoj.
 * @author andelalausevic
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
/**
 * Konstruktor klase FrmLogin.
 * Inicijalizuje komponente forme i postavlja lokaciju forme na centar ekrana.
 */
    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblUsernameError = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblUsernameError.setForeground(new java.awt.Color(255, 51, 51));

        lblPasswordError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassword)))
                    .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsernameError, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lblUsernameError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(lblPasswordError)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Metoda koja se poziva prilikom klika na dugme za prijavljivanje (btnLogin).
 * Pokušava izvršiti prijavljivanje korisnika na osnovu unetog korisničkog imena i lozinke.
 * Ako su uneti podaci ispravni, korisnik se prijavljuje i otvara se glavna forma (FrmMain).
 * U suprotnom, prikazuje se odgovarajuća greška.
 * 
 * @param evt Objekat koji predstavlja događaj klika na dugme
 */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            String username = getTxtUsername().getText().trim();
            String password = String.copyValueOf(getTxtPassword().getPassword());
            validateForm(username, password);

            User user = Communication.getInstance().login(username, password);

            JOptionPane.showMessageDialog(this, "Login success. Welcome " + user.getUsername());
            (new FrmMain(user)).setVisible(true);
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsernameError;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    /**
 * Dodaje prisluskivac dogadjaj na dugme za prijavljivanje (btnLogin).
 *
 * @param actionListener Prisluskivac dogadjaja koji se dodaje na dugme za prijavljivanje
 */
    public void loginAddActionListener(ActionListener actionListener) {
        btnLogin.addActionListener(actionListener);
    }
/**
 * Vraća JLabel komponentu za prikaz greške vezane za korisničko ime (lblUsernameError).
 *
 * @return JLabel komponenta za prikaz greške vezane za korisničko ime
 */
    public javax.swing.JLabel getLblUsernameError() {
        return lblUsernameError;
    }
/**
 * Postavlja JLabel komponentu za prikaz greške vezane za korisničko ime (lblUsernameError).
 *
 * @param lblUsernameError JLabel komponenta za prikaz greške vezane za korisničko ime
 */
    public void setLblUsernameError(javax.swing.JLabel lblUsernameError) {
        this.lblUsernameError = lblUsernameError;
    }
/**
 * Vraća JPasswordField komponentu za unos lozinke (txtPassword).
 *
 * @return JPasswordField komponenta za unos lozinke
 */
    public javax.swing.JPasswordField getTxtPassword() {
        return txtPassword;
    }
/**
 * Postavlja JPasswordField komponentu za unos lozinke (txtPassword).
 *
 * @param txtPassword JPasswordField komponenta za unos lozinke
 */
    public void setTxtPassword(javax.swing.JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }
/**
 * Vraća JTextField komponentu za unos korisničkog imena (txtUsername).
 *
 * @return JTextField komponenta za unos korisničkog imena
 */
    public javax.swing.JTextField getTxtUsername() {
        return txtUsername;
    }
/**
 * Postavlja JTextField komponentu za unos korisničkog imena (txtUsername).
 *
 * @param txtUsername JTextField komponenta za unos korisničkog imena
 */
    public void setTxtUsername(javax.swing.JTextField txtUsername) {
        this.txtUsername = txtUsername;
    }
/**
 * Vraća JLabel komponentu za prikaz greške vezane za lozinku (lblPasswordError).
 *
 * @return JLabel komponenta za prikaz greške vezane za lozinku
 */
    public JLabel getLblPasswordError() {
        return lblPasswordError;
    }
/**
 * Validira formu za prijavljivanje. Proverava da li su uneti korisničko ime i lozinka prazni.
 * Ukoliko su prazni, baca izuzetak sa odgovarajućom porukom.
 *
 * @param username Korisničko ime koje se validira
 * @param password Lozinka koja se validira
 * @throws Exception Izuzetak koji se baca ukoliko su korisničko ime i/ili lozinka prazni
 */
    private void validateForm(String username, String password) throws Exception {
        String errorMessage = "";
        if (username.isEmpty()) {
            errorMessage += "Username can not be empty!\n";
        }
        if (password.isEmpty()) {
            errorMessage += "Password can not be empty!\n";
        }
        if (!errorMessage.isEmpty()) {
            throw new Exception("You must fill username and password");
        }
    }

}
