package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import java.net.Socket;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import rs.ac.bg.fon.ps.domain.User;
import rs.ac.bg.fon.ps.view.form.util.FormMode;


public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    Socket socket = null;
    User user;
    public FrmMain(User user) {
        super("Projekat PS - Pocetna forma");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.user=user;
        prepare();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurrentUser = new javax.swing.JLabel();
        jmenuBarMain = new javax.swing.JMenuBar();
        jmenuKlijent = new javax.swing.JMenu();
        jmiKlijentCreate = new javax.swing.JMenuItem();
        jmenuPredstava = new javax.swing.JMenu();
        jmiPredstavaCreate = new javax.swing.JMenuItem();
        jmiPredstavaSearch = new javax.swing.JMenuItem();
        jmiPredstavaDelete = new javax.swing.JMenuItem();
        jmenuAbout = new javax.swing.JMenu();
        jmiRezervacijaCreate = new javax.swing.JMenuItem();
        jmiRezervacijaSearch = new javax.swing.JMenuItem();
        jmiRezervacijaChange = new javax.swing.JMenuItem();
        jmiRezervacijaDelete = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiKartaCreate = new javax.swing.JMenuItem();
        jmiKartaDelete = new javax.swing.JMenuItem();
        jMenuPlanGledanja = new javax.swing.JMenu();
        jmiPLanGledanjaCreate = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCurrentUser.setText("jLabel1");

        jmenuKlijent.setText("Klijent");
        jmenuKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuKlijentActionPerformed(evt);
            }
        });

        jmiKlijentCreate.setText("Create");
        jmiKlijentCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKlijentCreateActionPerformed(evt);
            }
        });
        jmenuKlijent.add(jmiKlijentCreate);

        jmenuBarMain.add(jmenuKlijent);

        jmenuPredstava.setText("Predstava");
        jmenuPredstava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuPredstavaActionPerformed(evt);
            }
        });

        jmiPredstavaCreate.setText("Create");
        jmiPredstavaCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPredstavaCreateActionPerformed(evt);
            }
        });
        jmenuPredstava.add(jmiPredstavaCreate);

        jmiPredstavaSearch.setText("Search");
        jmiPredstavaSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPredstavaSearchActionPerformed(evt);
            }
        });
        jmenuPredstava.add(jmiPredstavaSearch);

        jmiPredstavaDelete.setText("Delete");
        jmiPredstavaDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPredstavaDeleteActionPerformed(evt);
            }
        });
        jmenuPredstava.add(jmiPredstavaDelete);

        jmenuBarMain.add(jmenuPredstava);

        jmenuAbout.setText("Rezervacija");

        jmiRezervacijaCreate.setText("Create");
        jmiRezervacijaCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRezervacijaCreateActionPerformed(evt);
            }
        });
        jmenuAbout.add(jmiRezervacijaCreate);

        jmiRezervacijaSearch.setText("Search");
        jmiRezervacijaSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRezervacijaSearchActionPerformed(evt);
            }
        });
        jmenuAbout.add(jmiRezervacijaSearch);

        jmiRezervacijaChange.setText("Change");
        jmiRezervacijaChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRezervacijaChangeActionPerformed(evt);
            }
        });
        jmenuAbout.add(jmiRezervacijaChange);

        jmiRezervacijaDelete.setText("Delete");
        jmiRezervacijaDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRezervacijaDeleteActionPerformed(evt);
            }
        });
        jmenuAbout.add(jmiRezervacijaDelete);

        jmenuBarMain.add(jmenuAbout);

        jMenu1.setText("Karta");

        jmiKartaCreate.setText("Create");
        jmiKartaCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKartaCreateActionPerformed(evt);
            }
        });
        jMenu1.add(jmiKartaCreate);

        jmiKartaDelete.setText("Delete");
        jmiKartaDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKartaDeleteActionPerformed(evt);
            }
        });
        jMenu1.add(jmiKartaDelete);

        jmenuBarMain.add(jMenu1);

        jMenuPlanGledanja.setText("Plan Gledanja");

        jmiPLanGledanjaCreate.setText("Create");
        jmiPLanGledanjaCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPLanGledanjaCreateActionPerformed(evt);
            }
        });
        jMenuPlanGledanja.add(jmiPLanGledanjaCreate);

        jmenuBarMain.add(jMenuPlanGledanja);

        setJMenuBar(jmenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentUser)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuKlijentActionPerformed
    }//GEN-LAST:event_jmenuKlijentActionPerformed

    private void jmenuPredstavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuPredstavaActionPerformed
      
    }//GEN-LAST:event_jmenuPredstavaActionPerformed

    private void jmiKlijentCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKlijentCreateActionPerformed
       new FrmKlijent(this, true,FormMode.FORM_ADD).setVisible(true);
    }//GEN-LAST:event_jmiKlijentCreateActionPerformed

    private void jmiPredstavaCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPredstavaCreateActionPerformed
       new FrmPredstava(this, true, FormMode.FORM_ADD).setVisible(true);
    }//GEN-LAST:event_jmiPredstavaCreateActionPerformed

    private void jmiRezervacijaChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRezervacijaChangeActionPerformed
        // TODO add your handling code here:
        FrmPretragaRezervacija frm=new FrmPretragaRezervacija(this, rootPaneCheckingEnabled);
        frm.setVisible(true);
    }//GEN-LAST:event_jmiRezervacijaChangeActionPerformed

    private void jmiRezervacijaCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRezervacijaCreateActionPerformed
        // TODO add your handling code here:
        new FrmRezervacija(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jmiRezervacijaCreateActionPerformed

    private void jmiPredstavaSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPredstavaSearchActionPerformed
        // TODO add your handling code here:
        FrmViewShows frm=new FrmViewShows(this, rootPaneCheckingEnabled);
        frm.setVisible(true);
    }//GEN-LAST:event_jmiPredstavaSearchActionPerformed

    private void jmiKartaCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKartaCreateActionPerformed
        // TODO add your handling code here:
        new FrmKarta(this, true, FormMode.FORM_ADD).setVisible(true);
    }//GEN-LAST:event_jmiKartaCreateActionPerformed

    private void jmiPredstavaDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPredstavaDeleteActionPerformed
        // TODO add your handling code here:
        FrmViewShows frm=new FrmViewShows(this, rootPaneCheckingEnabled);
        frm.setVisible(true);
    }//GEN-LAST:event_jmiPredstavaDeleteActionPerformed

    private void jmiRezervacijaSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRezervacijaSearchActionPerformed
        // TODO add your handling code here:
        FrmPretragaRezervacija frm=new FrmPretragaRezervacija(this, rootPaneCheckingEnabled);
        frm.setVisible(true);
    }//GEN-LAST:event_jmiRezervacijaSearchActionPerformed

    private void jmiRezervacijaDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRezervacijaDeleteActionPerformed
        // TODO add your handling code here:
        FrmPretragaRezervacija frm=new FrmPretragaRezervacija(this, rootPaneCheckingEnabled);
        frm.setVisible(true);
    }//GEN-LAST:event_jmiRezervacijaDeleteActionPerformed

    private void jmiKartaDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKartaDeleteActionPerformed
        // TODO add your handling code here:
        new FrmViewTickets(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jmiKartaDeleteActionPerformed

    private void jmiPLanGledanjaCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPLanGledanjaCreateActionPerformed
        // TODO add your handling code here:
        new FrmPlanGledanja(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jmiPLanGledanjaCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuPlanGledanja;
    private javax.swing.JMenu jmenuAbout;
    private javax.swing.JMenuBar jmenuBarMain;
    private javax.swing.JMenu jmenuKlijent;
    private javax.swing.JMenu jmenuPredstava;
    private javax.swing.JMenuItem jmiKartaCreate;
    private javax.swing.JMenuItem jmiKartaDelete;
    private javax.swing.JMenuItem jmiKlijentCreate;
    private javax.swing.JMenuItem jmiPLanGledanjaCreate;
    private javax.swing.JMenuItem jmiPredstavaCreate;
    private javax.swing.JMenuItem jmiPredstavaDelete;
    private javax.swing.JMenuItem jmiPredstavaSearch;
    private javax.swing.JMenuItem jmiRezervacijaChange;
    private javax.swing.JMenuItem jmiRezervacijaCreate;
    private javax.swing.JMenuItem jmiRezervacijaDelete;
    private javax.swing.JMenuItem jmiRezervacijaSearch;
    private javax.swing.JLabel lblCurrentUser;
    // End of variables declaration//GEN-END:variables

    public void jmiProductNewAddActionListener(ActionListener actionListener) {
        jmiKlijentCreate.addActionListener(actionListener);
    }

   

    public JLabel getLblCurrentUser() {
        return lblCurrentUser;
    }

    public JMenuItem getJmiInvoiceNew() {
        return jmiPredstavaCreate;
    }

    private void prepare() {
        getLblCurrentUser().setText("Trenutni korisnik i ujedno jedini korisnik je: "+user.getUsername());
    }
    
}
