/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.net.Socket;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import rs.ac.bg.fon.ps.communication.Communication;
import rs.ac.bg.fon.ps.communication.LocalStorage;
import rs.ac.bg.fon.ps.PSCommon.communication.Operation;
import rs.ac.bg.fon.ps.PSCommon.communication.Receiver;
import rs.ac.bg.fon.ps.PSCommon.communication.Request;
import rs.ac.bg.fon.ps.PSCommon.communication.Response;
import rs.ac.bg.fon.ps.PSCommon.communication.Sender;
import rs.ac.bg.fon.ps.domain.Karta;
import rs.ac.bg.fon.ps.domain.PlanGledanja;
import rs.ac.bg.fon.ps.domain.Predstava;
import rs.ac.bg.fon.ps.domain.StavkaRezervacije;

import rs.ac.bg.fon.ps.view.form.util.FormMode;

public class FrmPredstava extends javax.swing.JDialog {

    /**
     * Creates new form FrmProduct
     */
    private LocalStorage localStorage = LocalStorage.getInstance();
    public FrmPredstava(java.awt.Frame parent, boolean modal, FormMode formMode) {
        super(parent, modal);
        initComponents();
        prepareView(formMode);
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblCapacity = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        txtPlace = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtCapacity = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form for show");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Predstava:"));

        lblId.setText("ID:");

        lblName.setText("Name:");

        lblDescription.setText("Place:");

        lblCapacity.setText("Capacity:");

        lblTime.setText("Time:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime)
                    .addComponent(lblCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtPlace)
                    .addComponent(txtTime)
                    .addComponent(txtCapacity, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(txtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacity)
                    .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(254, 254, 254)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave)
                        .addComponent(btnCancel))
                    .addComponent(btnDelete))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        try {
            Predstava predstava = new Predstava();
           // predstava.setPredstavaId(Integer.parseInt(getTxtID().getText().trim()));
            predstava.setNaziv(getTxtName().getText().trim());
            predstava.setMesto(getTxtPlace().getText().trim());
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MMM/yyyy HH:mm:ss");
                String dateStr = getTxtTime().getText().trim();
                LocalDateTime dateTime = LocalDateTime.parse(dateStr, dtf);
                        
           if(!dateTime.isAfter(LocalDateTime.now())){
               throw new Exception("Morate uneti datum koji je posle danasnjeg");
               //JOptionPane.showMessageDialog(this, "Morate uneti datum koji je posle danasnjeg");
           }
            predstava.setVreme(dateTime);
            try{
            predstava.setKapacitet(Integer.parseInt(getTxtCapcity().getText()));
            }catch(Exception e){
                 JOptionPane.showMessageDialog(this, "Kapacitet mora biti broj");
            }
            
            Communication.getInstance().addPredstava(predstava);
            JOptionPane.showMessageDialog(this, "Predstava successfully saved.");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage() +"\n"+"Predstava not saved","ERROR",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //TODO...
        int br=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete a show, potentially deleting all reservations and tickets and viewing plans for it.","WARNING",JOptionPane.YES_NO_OPTION);
        if(br==JOptionPane.YES_OPTION){
        Predstava pr=(Predstava) localStorage.getItemFromHashMap("Predstava");
        
        try {
            for(StavkaRezervacije st:getStavke()){
                if(st.getPredstavaId().getPredstavaId().equals(pr.getPredstavaId())){
                    for(Karta k:getKarte()){
                        if(st.getStavkaId().equals(k.getStavkaId().getStavkaId())){
                            deleteKarta(k);
                        }
                    }
                    deleteStavke(st);
                }
            }
            for(PlanGledanja pl:getPlan()){
                if(pl.getPredstavaId().getPredstavaId().equals(pr.getPredstavaId())){
                    deletePlanGledanja(pl);
                }
            }
            Communication.getInstance().deleteShow(pr);
            JOptionPane.showMessageDialog(this, "Predstava successfully deleted.");
            this.dispose();
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this, ex.getMessage() +"\n"+"System can not delete this show","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        }
            
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCapacity;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPlace;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

 
    public JButton getBtnSave() {
        return btnSave;
    }


    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JLabel getLblId() {
        return lblId;
    }

  

    public JLabel getLblCapacity() {
        return lblCapacity;
    }

    public JLabel getLblName() {
        return lblName;
    }

    public JLabel getLblTime() {
        return lblTime;
    }

    public JTextField getTxtPlace() {
        return txtPlace;
    }
      public JTextField getTxtTime() {
        return txtTime;
    }

    public JTextField getTxtID() {
        return txtID;
    }

    public JTextField getTxtName() {
        return txtName;
    }

    public JTextField getTxtCapcity() {
        return txtCapacity;
    }

    public void addSaveBtnActionListener(ActionListener actionListener) {
        btnSave.addActionListener(actionListener);
    }

  

    public void addCancelBtnActionListener(ActionListener actionListener) {
        btnCancel.addActionListener(actionListener);
    }

    public void addDeleteBtnActionListener(ActionListener actionListener) {
        btnDelete.addActionListener(actionListener);
    }


    private void prepareView(FormMode formMode) {
       
        setupComponents(formMode);

    }

    

   
    private void setupComponents(FormMode formMode) {
        switch (formMode) {
            case FORM_ADD:
                getBtnCancel().setEnabled(true);
                getBtnDelete().setEnabled(false);
        
                getBtnSave().setEnabled(true);
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MMM/yyyy HH:mm:ss");
                String dateStr = "18/Feb/2023 20:45:25";
                //LocalDateTime dateTime = LocalDateTime.parse(dateStr, dtf);
                getTxtTime().setText(dateStr);
                getTxtID().setEnabled(false);
                getTxtName().setEnabled(true);
                getTxtPlace().setEnabled(true);
                getTxtCapcity().setEnabled(true);
                getTxtTime().setEnabled(true);
                
                break;
            case FORM_VIEW:
                JOptionPane.showMessageDialog(this,"Sistem je ucitao predstavu.");
                getBtnCancel().setEnabled(true);
                getBtnDelete().setEnabled(true);
        
                getBtnSave().setEnabled(false);

                //zabrani izmenu vrednosti
                getTxtID().setEnabled(false);
                getTxtName().setEnabled(false);
                getTxtCapcity().setEnabled(false);
                getTxtPlace().setEnabled(false);
                getTxtTime().setEnabled(false);
                setForView();
                

                //get product
                //TODO..
                break;
            case FORM_EDIT:
                getBtnCancel().setEnabled(true);
                getBtnDelete().setEnabled(false);
      
                getBtnSave().setEnabled(false);

                //zabrani izmenu vrednosti
                getTxtID().setEnabled(false);
                getTxtName().setEnabled(true);
                getTxtCapcity().setEnabled(true);
                getTxtPlace().setEnabled(true);
                getTxtTime().setEnabled(true);
                
                break;
        }
    }

    private void setForView() {
        Predstava pr=(Predstava) localStorage.getItemFromHashMap("Predstava");
        getTxtID().setText(pr.getPredstavaId().toString());
        getTxtName().setText(pr.getNaziv());
        
        getTxtTime().setText(pr.getVreme().toString());
        getTxtPlace().setText(pr.getMesto());
        getTxtCapcity().setText(pr.getKapacitet().toString());
    }
     private List<StavkaRezervacije> getStavke() throws Exception {
         return Communication.getInstance().getAllItemReservations();
    }
      private List<Karta> getKarte() throws Exception {
         return Communication.getInstance().getAllTickets();
    }
      private void deleteStavke(StavkaRezervacije st) throws Exception {
        Communication.getInstance().deleteStavka(st);
    }

    private void deleteKarta(Karta k) throws Exception {
        Communication.getInstance().deleteTicket(k);
    }

    private List<PlanGledanja> getPlan() throws Exception {
        return Communication.getInstance().getAllPlan();
    }

    private void deletePlanGledanja(PlanGledanja pl) throws Exception {
        Communication.getInstance().deletePlan(pl);
    }

}
