package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.net.Socket;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import rs.ac.bg.fon.ps.communication.Communication;
import rs.ac.bg.fon.ps.PSCommon.communication.Operation;
import rs.ac.bg.fon.ps.PSCommon.communication.Receiver;
import rs.ac.bg.fon.ps.PSCommon.communication.Request;
import rs.ac.bg.fon.ps.PSCommon.communication.Response;
import rs.ac.bg.fon.ps.PSCommon.communication.Sender;
import rs.ac.bg.fon.ps.PSCommon.domain.Karta;
import rs.ac.bg.fon.ps.PSCommon.domain.Klijent;
import rs.ac.bg.fon.ps.PSCommon.domain.Predstava;
import rs.ac.bg.fon.ps.PSCommon.domain.Rezervacija;
import rs.ac.bg.fon.ps.PSCommon.domain.StavkaRezervacije;
import rs.ac.bg.fon.ps.view.form.componenet.table.ReservationsTableModel;
/**
 * Forma koja radi po principu pretrazivanja klijenata
 * onda se vidi da li klijent ima rezervaciju
 * ukoliko je to slucaj setuju se sve vrednosti njene
 * i moguce je menjati je ili obrisati ili samo pogledati
 * @author andelalausevic
 */
public class FrmPretragaRezervacija extends javax.swing.JDialog {
   
    /**
    * Lista stavkirezervacija ali novih koje ce se dodati pri auzuriranju rezervacije
    */
     private ArrayList<StavkaRezervacije> nove;
     /**
    * Lista stavkirezervacija ali starih koje ce se nece dodati pri auzuriranju rezervacije
    */
      private ArrayList<StavkaRezervacije> stare=new ArrayList<>();
      /**
    * Lista stavkirezervacija ali onih za izbacivanje koje se nece  dodati pri auzuriranju rezervacije
    */
      private ArrayList<StavkaRezervacije> zaIzbacivanje=new ArrayList<>();
      /**
    * Lista stavkirezervacija  koje ce se dodati pri auzuriranju rezervacije
    */
      private ArrayList<StavkaRezervacije> zaDodavanje=new ArrayList<>();
      /**
    * Lista stavkirezervacija sa kojima ne treba nista da se radi  pri auzuriranju rezervacije
    */
      private ArrayList<StavkaRezervacije> nista=new ArrayList<>();
     /**
 * Konstruktor klase FrmPretragaRezervacija.
 *
 * @param parent Roditeljski okvir
 * @param modal Modalnost prozora
 */
    public FrmPretragaRezervacija(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInvoiceId = new javax.swing.JLabel();
        txtInvoiceId = new javax.swing.JTextField();
        lblNumberOfShow = new javax.swing.JLabel();
        txtInvoiceNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        btnRemoveInvoiceItem = new javax.swing.JButton();
        panelPredstava = new javax.swing.JPanel();
        lblPredstava = new javax.swing.JLabel();
        cbProduct = new javax.swing.JComboBox<>();
        lblDiscount = new javax.swing.JLabel();
        txtProductPrice = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtProductQuantity = new javax.swing.JTextField();
        lblWatched = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        cbWatched = new javax.swing.JComboBox<>();
        btnSaveProduct1 = new javax.swing.JButton();
        jClient = new javax.swing.JLabel();
        cbClients = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        cbReservations = new javax.swing.JComboBox<>();
        btnChose = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblChose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form for search reservations");

        lblInvoiceId.setText("Id:");

        txtInvoiceId.setEditable(false);

        lblNumberOfShow.setText("Number of shows:");

        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInvoice);

        btnRemoveInvoiceItem.setText("Remove");
        btnRemoveInvoiceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveInvoiceItemActionPerformed(evt);
            }
        });

        panelPredstava.setBorder(javax.swing.BorderFactory.createTitledBorder("Predstava"));

        lblPredstava.setText("Predstava:");

        lblDiscount.setText("Discount:");

        lblQuantity.setText("Quantity:");

        lblWatched.setText("Watched:");

        btnAddProduct.setText("Add");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        cbWatched.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ne", "da" }));

        javax.swing.GroupLayout panelPredstavaLayout = new javax.swing.GroupLayout(panelPredstava);
        panelPredstava.setLayout(panelPredstavaLayout);
        panelPredstavaLayout.setHorizontalGroup(
            panelPredstavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPredstavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPredstavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPredstava, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiscount)
                    .addComponent(lblQuantity)
                    .addComponent(lblWatched))
                .addGap(74, 74, 74)
                .addGroup(panelPredstavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPredstavaLayout.createSequentialGroup()
                        .addGroup(panelPredstavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbProduct, 0, 360, Short.MAX_VALUE)
                            .addComponent(txtProductPrice)
                            .addComponent(txtProductQuantity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddProduct))
                    .addComponent(cbWatched, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelPredstavaLayout.setVerticalGroup(
            panelPredstavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPredstavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPredstavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPredstava, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPredstavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiscount)
                    .addComponent(txtProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPredstavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantity)
                    .addComponent(txtProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPredstavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWatched)
                    .addComponent(cbWatched, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSaveProduct1.setText("Cancel");
        btnSaveProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProduct1ActionPerformed(evt);
            }
        });

        jClient.setText("Select client to find reservation:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnChange.setText("Enable Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnChose.setText("Choose");
        btnChose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoseActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Save Changes");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblChose.setText("Choose your reservation to show:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChose)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoveInvoiceItem)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblInvoiceId, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(118, 118, 118)
                                        .addComponent(txtInvoiceId, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblNumberOfShow, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblChose, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                            .addComponent(jClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSearch)
                                            .addComponent(txtInvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbClients, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 246, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(panelPredstava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 256, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnSaveProduct1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnChange)
                                        .addGap(15, 15, 15)
                                        .addComponent(btnSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(btnDelete)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInvoiceId)
                    .addComponent(txtInvoiceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumberOfShow))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblChose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveInvoiceItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPredstava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveProduct1)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnChange)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Metoda koja se poziva kada se pritisne dugme za dodavanje predstave u rezervaciju.
 *Gleda se koja je predstava izabrana za nju se unosi popust, koliko sedista se zeli rezervisati
 * i da li je vec korisnik gledao
 * zatim se pojavljuje ta stavka rezervacije u tabeli
 * i dodaje se na listu stavki zadodavanje
 * ukoliko nisu podaci dobro uneti bice poruka o gresci
 * @param evt Događaj akcije
 */
    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        try {
                    Predstava predstava = (Predstava) getCbPredstava().getSelectedItem();
                    Integer discount =  Integer.parseInt(getTxtDiscount().getText().trim());
                    Integer quantity = Integer.parseInt(getTxtProductQuantity().getText().trim());
                    boolean watched=true;
                    if(cbWatched.getSelectedItem().equals("ne")){
                        watched=false;
                    }
                    ReservationsTableModel model = (ReservationsTableModel) getTblRezervacija().getModel();
                    model.addInvoiceItem(predstava, quantity, discount, watched);
                    zaDodavanje.add(new StavkaRezervacije(null, discount, quantity, watched,  ((ReservationsTableModel) getTblRezervacija().getModel()).getInvoice(), predstava));

                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Invalid predstava data!", "Error", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_btnAddProductActionPerformed
/**
 * Metoda koja se poziva kada se pritisne dugme za uklanjanje stavke rezervacije.
 *uzima se selektovana iz tabele stavka
 * dodaje se na lsitu zaizbacivanje i izbacuje se iz tabele
 * @param evt Događaj akcije
 */
    private void btnRemoveInvoiceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveInvoiceItemActionPerformed
        int rowIndex = getTblRezervacija().getSelectedRow();
                ReservationsTableModel model = (ReservationsTableModel) getTblRezervacija().getModel();
                if (rowIndex >= 0) {
                          zaIzbacivanje.add(((ReservationsTableModel) getTblRezervacija().getModel()).getInvoice().getStavke().get(rowIndex));
                    System.out.println(((ReservationsTableModel) getTblRezervacija().getModel()).getInvoice().getStavke().get(rowIndex));
                    model.removeInvoiceItem(rowIndex);
             
                } else {
                    JOptionPane.showMessageDialog(this, "Rezervacija item is not selected!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
    }//GEN-LAST:event_btnRemoveInvoiceItemActionPerformed
/**
 * 
 *Ova metoda se ne koristi.
 * @param evt Događaj akcije
 */
    private void btnSaveProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProduct1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSaveProduct1ActionPerformed
/**
 * Metoda koja se poziva kada se pritisne dugme za odabir rezervacije.
 *Kada se izabere rezervacija iz padajuceg menija
 * popunjavaju se njene vrednosti na formi
 * njene stavke se dodaju u listu nove
 * ukoliko korisnik nije izabrao rezervaciju izaci ce mu poruka o tome
 * @param evt Događaj akcije
 */
    private void btnChoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoseActionPerformed
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:
            if(getCbReservations().getSelectedIndex()!=-1){
                Rezervacija reserve= (Rezervacija)getCbReservations().getSelectedItem();
                //List<StavkaRezervacije> allReservations=reserve.getStavke();
                List<StavkaRezervacije> stavke=getStavke();
                nove=new ArrayList<>();
                
                for(StavkaRezervacije st:stavke){
                    if(st.getRezervacijaId().getRezervacijaId().equals(reserve.getRezervacijaId())){
                        nove.add(st);
                        fillIt(st);
                       
                    }
                    
                }
                
                reserve.setStavke(nove);
                ReservationsTableModel model = new ReservationsTableModel(reserve);
                getTblRezervacija().setModel(model);
                getTxtInvoiceId().setText(reserve.getRezervacijaId().toString());
                getTxtInvoiceNumber().setText(reserve.getBrojPredstave().toString());
                prepareForChangeDelete();
                                JOptionPane.showMessageDialog(this,"Sistem je ucitao rezervaciju");

                
            }
            else{
                JOptionPane.showMessageDialog(this,"Sistem ne moze da ucita rezervaciju verovatno je niste selektovali");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaRezervacija.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_btnChoseActionPerformed
/**
 * Metoda koja se poziva kada se pritisne dugme za pretragu rezervacija.
 *Ukoliko klijent ne postoji izlazi odgovarajuca poruka
 * ukoliko postoji combobox se puni njegovim rezervacijama
 * @param evt Događaj akcije
 */
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            // TODO add your handling code here:
            if(getCbClient().getSelectedIndex()!=-1){
                Klijent client= (Klijent)getCbClient().getSelectedItem();
                List<Rezervacija> allReservations=getReservations();
            List<Rezervacija> selectedReservations=new ArrayList<>();
            for(Rezervacija r:allReservations){
                if(r.getKlijentId().equals(client)){
                    selectedReservations.add(r);
                }
            }
            if(selectedReservations.isEmpty()){
                JOptionPane.showMessageDialog(this,"Sistem ne moze da nadje rezervacije po zadatoj vrednosti"+ "\n"+" Za datog klijenta nema rezervacija");
            }
            else{
            JOptionPane.showMessageDialog(this,"Sistem je nasao rezervacije po zadatoj vrednosti");    
            getCbReservations().setModel(new DefaultComboBoxModel(selectedReservations.toArray()));
            getCbReservations().setSelectedIndex(-1);
            prepareForChoose();
            }
            }
            else{
                JOptionPane.showMessageDialog(this,"Niste selektovali klijenta");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaRezervacija.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btnSearchActionPerformed
/**
 * Metoda koja pritiskom dugmeta da se dozvoli da se menja rezervacija poziva metodu da pripremi formu za izmenu rezervacije
 * @param evt dogadjaj koji je okinuo radnju
 */
    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        prepareChange();
     
    }//GEN-LAST:event_btnChangeActionPerformed
/**
 * Metoda koja se poziva kada se pritisne dugme za čuvanje izmena rezervacije.
 *Uzimaju se podaci sa forme
 * ako broj predstavi koji je naveden se ne poklapa sa brojem stavki izaci ce greska i poruka o gresci
 * ukoliko jeste sve okej auzurirace se rezervacija
 * dodaju se i izbacuju stavke u zavisnosti od stanja na tabeli i u listama sta je stavljeno u proslim metodama
 * ispisace se poruka o uspesnosti ili neuspesnosti akcije
 * @param evt Događaj akcije
 */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
                    
                    ReservationsTableModel model = (ReservationsTableModel) getTblRezervacija().getModel();
                    Rezervacija reserve= (Rezervacija)getCbReservations().getSelectedItem();
                    reserve.setBrojPredstave(Integer.parseInt(getTxtInvoiceNumber().getText().trim()));
                    reserve.setKlijentId((Klijent) getCbClient().getSelectedItem());
                    if(!(reserve.getBrojPredstave()==reserve.getStavke().size())){
                        System.out.println("JOK");
                        throw new Exception("Broj predstava mora biti jednak broju unetih predstavi u tabeli");
                    }

                    updateInvoice(reserve);
                    /*if(!nove.isEmpty()){
                       
                    for(StavkaRezervacije s:nove){
                        System.out.println("Koje sve u tabeli" + s.getPredstavaId());
                        getBackDifferent(s);
                    }
                    }
                    if(!stare.isEmpty()){
                    for(StavkaRezervacije st:stare){
                        getBackDifferentDelete(st);
                    }
                    }
                    if(!zaDodavanje.isEmpty()){
                    for(StavkaRezervacije st:zaDodavanje){
                        addStavke(st);
                    }
                    }
                    if(!zaIzbacivanje.isEmpty()){
                    for(StavkaRezervacije st:zaIzbacivanje){
                        deleteStavke(st);
                    }
                  
                    }*/
                    if(!zaDodavanje.isEmpty()){
                    for(StavkaRezervacije st:zaDodavanje){
                        addStavke(st);
                    }
                    }
                    if(!zaIzbacivanje.isEmpty()){
                    for(StavkaRezervacije st:zaIzbacivanje){
                        for(Karta k:getKarte()){
                            if(k.getStavkaId().getStavkaId().equals(st.getStavkaId())){
                                 deleteKarta(k);
                        }
                        }
                        deleteStavke(st);
                    }
                    }
                    zaDodavanje=new ArrayList<>();
                    zaIzbacivanje=new ArrayList<>();
                    JOptionPane.showMessageDialog(this, "Rezervacija is updated");
                    this.dispose();
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Rezervacija is not updated! " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

                }
      
    }//GEN-LAST:event_btnSaveActionPerformed
/**
 * Metoda koja se poziva kada se pritisne dugme za brisanje rezervacije.
 *Pita se korisnik da li je siguran
 * ukoliko je odgovor da brisu se sve stavke i karte koje su vezane za rezervaciju
 * i ispisace se poruka o uspesnosti
 * @param evt Događaj akcije
 */
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int br=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete a reservation, potentially deleting tickets for reservation.","WARNING",JOptionPane.YES_NO_OPTION);
        if(br==JOptionPane.YES_OPTION){
          Rezervacija reserve= (Rezervacija)getCbReservations().getSelectedItem();
        try {
            
            for(StavkaRezervacije st:reserve.getStavke()){
                for(Karta k:getKarte()){
                    if(k.getStavkaId().getStavkaId().equals(st.getStavkaId())){
                        deleteKarta(k);
                    }
                }
                deleteStavke(st);
            }
            Communication.getInstance().deleteReserve(reserve);
            JOptionPane.showMessageDialog(this, "Rezervacija successfully deleted.");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Rezervacija not deleted."+ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
/**
 * Metoda koja vraća JTextField komponentu za ID rezervacije.
 *
 * @return JTextField komponenta za ID rezervacije
 */
    public JTextField getTxtRezervacijaId() {
        return txtInvoiceId;
    }
/**
 * Metoda koja vraća JLabel komponentu za ID rezervacije.
 *
 * @return JLabel komponenta za ID rezervacije
 */
    public JLabel getLblRezervacijaId() {
        return lblInvoiceId;
    }
    /**
 * Metoda koja vraća JLabel komponentu za broj predstava.
 *
 * @return JLabel komponenta za broj predstava
 */
    public JLabel getLblNumberOfShow() {
        return lblNumberOfShow;
    }
    /**
 * Metoda koja vraća JLabel komponentu za naziv predstave.
 *
 * @return JLabel komponenta za naziv predstave
 */
    public JLabel getLblShow() {
        return lblPredstava;
    }
    /**
 * Metoda koja vraća JLabel komponentu za popust.
 *
 * @return JLabel komponenta za popust
 */
     public JLabel getLblDiscount() {
        return lblDiscount;
    }
     /**
 * Metoda koja vraća JLabel komponentu za količinu.
 *
 * @return JLabel komponenta za količinu
 */
      public JLabel getLblQuantity() {
        return lblQuantity;
    }
      /**
 * Metoda koja vraća JLabel komponentu za praćenje gledanja.
 *
 * @return JLabel komponenta za praćenje gledanja
 */
    public JLabel getLblWatched() {
        return lblWatched;
    }
    /**
 * Metoda koja vraća JPanel komponentu za predstavu.
 *
 * @return JPanel komponenta za predstavu
 */
    public JPanel getPanelPredstava(){
        return panelPredstava;
    }
    /**
 * Metoda koja vraća JLabel komponentu za klijenta.
 *
 * @return JLabel komponenta za klijenta
 */
     public JLabel getLblClient() {
        return jClient;
    }
     /**
 * Metoda koja vraća JLabel komponentu za odabir.
 *
 * @return JLabel komponenta za odabir
 */
     public JLabel getLblChose() {
        return lblChose;
    }
/**
 * Metoda koja vraća JComboBox komponentu za odabir predstave.
 *
 * @return JComboBox komponenta za odabir predstave
 */
    public JComboBox<Object> getCbPredstava() {
        return cbProduct;
    }
    /**
 * Metoda koja vraća JComboBox komponentu za odabir klijenta.
 *
 * @return JComboBox komponenta za odabir klijenta
 */
    public JComboBox<Object> getCbClient() {
        return cbClients;
    }
    /**
 * Metoda koja vraća JComboBox komponentu za odabir rezervacije.
 *
 * @return JComboBox komponenta za odabir rezervacije
 */
    public JComboBox<Object> getCbReservations() {
        return cbReservations;
    }
    /**
 * Metoda koja vraća JComboBox komponentu za odabir praćenja gledanja.
 *
 * @return JComboBox komponenta za odabir praćenja gledanja
 */
      public JComboBox<String> getCbWatched() {
        return cbWatched;
    }
      /**
 * Metoda koja vraća JTable komponentu za prikaz rezervacija.
 *
 * @return JTable komponenta za prikaz rezervacija
 */

    public JTable getTblRezervacija() {
        return tblInvoice;
    }
/**
 * Metoda koja vraća JLabel komponentu za broj predstava.
 *
 * @return JLabel komponenta za broj predstava
 */
   public JLabel getNumberOfShows(){
       return lblNumberOfShow;
   }
   /**
 * Metoda koja vraća JButton komponentu za pretragu rezervacija.
 *
 * @return JButton komponenta za pretragu rezervacija
 */
   public JButton getBtnSearch (){
       return btnSearch;
   }
   /**
 * Metoda koja vraća JButton komponentu za odabir rezervacije.
 *
 * @return JButton komponenta za odabir rezervacije
 */
   public JButton getBtnChoose(){
       return btnChose;
   }
   /**
 * Metoda koja vraća JButton komponentu za uklanjanje stavke rezervacije.
 *
 * @return JButton komponenta za uklanjanje stavke rezervacije
 */
   public JButton getBtnRemove(){
       return btnRemoveInvoiceItem;
   }
   /**
 * Metoda koja vraća JButton komponentu za dodavanje stavki u rezervaciju.
 *
 * @return JButton komponenta za dodavanje stavki u rezervaciju
 */
   public JButton getBtnAddProduct(){
       return btnAddProduct;
   }
   /**
 * Metoda koja vraća JButton komponentu za brisanje rezervacije.
 *
 * @return JButton komponenta za brisanje rezervacije
 */
    public JButton getBtnDelete(){
       return btnDelete;
   }
    /**
 * Metoda koja vraća JButton komponentu za čuvanje rezervacije.
 *
 * @return JButton komponenta za čuvanje rezervacije
 */
    public JButton getBtnSave(){
       return btnSave;
   }
    /**
 * Metoda koja vraća JButton komponentu za promenu rezervacije.
 *
 * @return JButton komponenta za promenu rezervacije
 */

    public JButton getBtnChange(){
       return btnChange;
   }
    /**
 * Metoda koja vraća JTextField komponentu za broj rezervacije.
 *
 * @return JTextField komponenta za broj rezervacije
 */
    public JTextField getTxtInvoiceNumber() {
        return txtInvoiceNumber;
    }
    /**
 * Metoda koja vraća JTextField komponentu za identifikator rezervacije.
 *
 * @return JTextField komponenta za identifikator rezervacije
 */
     public JTextField getTxtInvoiceId() {
        return txtInvoiceId;
    }
     /**
 * Metoda koja vraća JScrollPane komponentu za prikaz rezervacija.
 *
 * @return JScrollPane komponenta za prikaz rezervacija
 */
      public JScrollPane getScrol() {
        return jScrollPane1;
    }

  
    
 /**
 * Metoda koja vraća JTextField komponentu za popust.
 *
 * @return JTextField komponenta za popust
 */
    public JTextField getTxtDiscount() {
        return txtProductPrice;
    }
/**
 * Metoda koja vraća JTextField komponentu za količinu sedista.
 *
 * @return JTextField komponenta za količinu sedista
 */
    public JTextField getTxtProductQuantity() {
        return txtProductQuantity;
    }
   /**
 * Metoda za dodavanje ActionListenera na dugme za dodavanje stavke u rezervaciju.
 *
 * @param actionListener ActionListener koji se dodaje na dugme za dodavanje stavke
 */

    public void addBtnAddProductActionListener(ActionListener actionListener) {
        btnAddProduct.addActionListener(actionListener);
    }
/**
 * Metoda za dodavanje ActionListenera na dugme za uklanjanje stavke rezervacije.
 *
 * @param actionListener ActionListener koji se dodaje na dugme za uklanjanje stavke rezervacije
 */
    public void addBtnRemoveInvoiceItemActionListener(ActionListener actionListener) {
        btnRemoveInvoiceItem.addActionListener(actionListener);
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnChose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRemoveInvoiceItem;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveProduct1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<Object> cbClients;
    private javax.swing.JComboBox<Object> cbProduct;
    private javax.swing.JComboBox<Object> cbReservations;
    private javax.swing.JComboBox<String> cbWatched;
    private javax.swing.JLabel jClient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChose;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblInvoiceId;
    private javax.swing.JLabel lblNumberOfShow;
    private javax.swing.JLabel lblPredstava;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblWatched;
    private javax.swing.JPanel panelPredstava;
    private javax.swing.JTable tblInvoice;
    private javax.swing.JTextField txtInvoiceId;
    private javax.swing.JTextField txtInvoiceNumber;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtProductQuantity;
    // End of variables declaration//GEN-END:variables
/**
 * Metoda koja priprema prikaz forme za rezervaciju.
 * Postavlja modele ComboBox komponenti za izbor predstave i klijenta.
 * Takođe, popunjava tabelu sa rezervacijama.
 */
    private void prepareView() {
        try {
            getCbPredstava().setModel(new DefaultComboBoxModel(getProducts().toArray()));
            getCbPredstava().setSelectedIndex(-1);
             getCbClient().setModel(new DefaultComboBoxModel(getClients().toArray()));
            getCbClient().setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaRezervacija.class.getName()).log(Level.SEVERE, null, ex);
        }
        prepare();
        

    }
    /**
 * Priprema vidljivost komponenti na korisničkom interfejsu.
 * Postavlja vidljivost određenih komponenti na true ili false u skladu sa postavkama.
 * Vidljive komponente:
 * - getCbClient() - ComboBox za izbor klijenta
 * - getLblClient() - Labela za prikaz teksta "Klijent"
 * - getBtnSearch() - Dugme za pretragu rezervacija
 *
 * Nevidljive komponente:
 * - getLblChose() - Labela za prikaz teksta "Izaberite rezervaciju"
 * - getTxtInvoiceId() - Tekstualno polje za prikaz ID rezervacije
 * - getLblRezervacijaId() - Labela za prikaz teksta "ID rezervacije"
 * - getLblNumberOfShow() - Labela za prikaz teksta "Broj predstave"
 * - getTxtInvoiceNumber() - Tekstualno polje za prikaz broja predstave
 * - getCbReservations() - ComboBox za izbor rezervacije
 * - getBtnChoose() - Dugme za izbor rezervacije
 * - getScrol() - Scroll panel
 * - getTblRezervacija() - Tabela za prikaz rezervacija
 * - getBtnRemove() - Dugme za uklanjanje stavke rezervacije
 * - getPanelPredstava() - Panel za prikaz predstave
 * - getCbPredstava() - ComboBox za izbor predstave
 * - getLblShow() - Labela za prikaz teksta "Predstava"
 * - getBtnAddProduct() - Dugme za dodavanje stavke rezervacije
 * - getLblDiscount() - Labela za prikaz teksta "Popust"
 * - getTxtDiscount() - Tekstualno polje za unos popusta
 * - getLblQuantity() - Labela za prikaz teksta "Količina"
 * - getTxtProductQuantity() - Tekstualno polje za unos količine
 * - getLblWatched() - Labela za prikaz teksta "Gledano"
 * - getCbWatched() - ComboBox za izbor opcije "Gledano"
 * - getBtnChange() - Dugme za izmenu rezervacije
 * - getBtnDelete() - Dugme za brisanje rezervacije
 * - getBtnSave() - Dugme za čuvanje rezervacije
 */
    private void prepare() {
      getLblChose().setVisible(false);
      getTxtInvoiceId().setVisible(false);
      getLblRezervacijaId().setVisible(false);
      getLblNumberOfShow().setVisible(false);
      getTxtInvoiceNumber().setVisible(false);

      getCbClient().setVisible(true);
      getLblClient().setVisible(true);
      getBtnSearch().setVisible(true);
      
      getCbReservations().setVisible(false);
      getBtnChoose().setVisible(false);
      
      getScrol().setVisible(false);
      getTblRezervacija().setVisible(false);
      getBtnRemove().setVisible(false);
      
      getPanelPredstava().setVisible(false);
      getCbPredstava().setVisible(false);
      getLblShow().setVisible(false);
      getBtnAddProduct().setVisible(false);
      getLblDiscount().setVisible(false);
      getTxtDiscount().setVisible(false);
      getLblQuantity().setVisible(false);
      getTxtProductQuantity().setVisible(false);
      getLblWatched().setVisible(false);
      getCbWatched().setVisible(false);
      getBtnChange().setVisible(false);
      getBtnDelete().setVisible(false);   
      getBtnSave().setVisible(false);
    }
    /**
 * Priprema vidljivost komponenti na korisničkom interfejsu za izbor rezervacije.
 * Postavlja vidljivost određenih komponenti na true ili false u skladu sa postavkama.
 * Vidljive komponente:
 * - getLblChose() - Labela za prikaz teksta "Izaberite rezervaciju"
 * - getCbClient() - ComboBox za izbor klijenta
 * - getLblClient() - Labela za prikaz teksta "Klijent"
 * - getBtnSearch() - Dugme za pretragu rezervacija
 * - getCbReservations() - ComboBox za izbor rezervacije
 * - getBtnChoose() - Dugme za izbor rezervacije
 *
 * Nevidljive komponente:
 * - getTxtInvoiceId() - Tekstualno polje za prikaz ID rezervacije
 * - getLblRezervacijaId() - Labela za prikaz teksta "ID rezervacije"
 * - getLblNumberOfShow() - Labela za prikaz teksta "Broj predstave"
 * - getTxtInvoiceNumber() - Tekstualno polje za prikaz broja predstave
 * - getScrol() - Scroll panel
 * - getTblRezervacija() - Tabela za prikaz rezervacija
 * - getBtnRemove() - Dugme za uklanjanje stavke rezervacije
 * - getPanelPredstava() - Panel za prikaz predstave
 * - getCbPredstava() - ComboBox za izbor predstave
 * - getLblShow() - Labela za prikaz teksta "Predstava"
 * - getBtnAddProduct() - Dugme za dodavanje stavke rezervacije
 * - getLblDiscount() - Labela za prikaz teksta "Popust"
 * - getTxtDiscount() - Tekstualno polje za unos popusta
 * - getLblQuantity() - Labela za prikaz teksta "Količina"
 * - getTxtProductQuantity() - Tekstualno polje za unos količine
 * - getLblWatched() - Labela za prikaz teksta "Gledano"
 * - getCbWatched() - ComboBox za izbor opcije "Gledano"
 * - getBtnChange() - Dugme za izmenu rezervacije
 * - getBtnDelete() - Dugme za brisanje rezervacije
 * - getBtnSave() - Dugme za čuvanje rezervacije
 */
    private void prepareForChoose() {
      getLblChose().setVisible(true);
      getTxtInvoiceId().setVisible(false);
      getLblRezervacijaId().setVisible(false);
      getLblNumberOfShow().setVisible(false);
      getTxtInvoiceNumber().setVisible(false);

      getCbClient().setVisible(true);
      getLblClient().setVisible(true);
      getBtnSearch().setVisible(true);
      
      getCbReservations().setVisible(true);
      getBtnChoose().setVisible(true);
      
      getScrol().setVisible(false);
      getTblRezervacija().setVisible(false);
      getBtnRemove().setVisible(false);
      
      getPanelPredstava().setVisible(false);
      getCbPredstava().setVisible(false);
      getLblShow().setVisible(false);
      getBtnAddProduct().setVisible(false);
      getLblDiscount().setVisible(false);
      getTxtDiscount().setVisible(false);
      getLblQuantity().setVisible(false);
      getTxtProductQuantity().setVisible(false);
      getLblWatched().setVisible(false);
      getCbWatched().setVisible(false);
      getBtnChange().setVisible(false);
      getBtnDelete().setVisible(false);   
      getBtnSave().setVisible(false);
    }
    /**
 * Priprema vidljivost komponenti na korisničkom interfejsu za izmenu i brisanje rezervacije.
 * Postavlja vidljivost određenih komponenti na true ili false u skladu sa postavkama.
 * Vidljive komponente:
 * - getLblNumberOfShow() - Labela za prikaz teksta "Broj predstave"
 * - getTxtInvoiceNumber() - Tekstualno polje za prikaz broja predstave
 * - getCbClient() - ComboBox za izbor klijenta
 * - getLblClient() - Labela za prikaz teksta "Klijent"
 * - getBtnSearch() - Dugme za pretragu rezervacija
 * - getCbReservations() - ComboBox za izbor rezervacije
 * - getBtnChoose() - Dugme za izbor rezervacije
 * - getScrol() - Scroll panel
 * - getTblRezervacija() - Tabela za prikaz rezervacija
 * - getBtnChange() - Dugme za izmenu rezervacije
 * - getBtnDelete() - Dugme za brisanje rezervacije
 *
 * Nevidljive komponente:
 * - getTxtInvoiceId() - Tekstualno polje za prikaz ID rezervacije
 * - getLblRezervacijaId() - Labela za prikaz teksta "ID rezervacije"
 * - getPanelPredstava() - Panel za prikaz predstave
 * - getCbPredstava() - ComboBox za izbor predstave
 * - getLblShow() - Labela za prikaz teksta "Predstava"
 * - getBtnAddProduct() - Dugme za dodavanje stavke rezervacije
 * - getLblDiscount() - Labela za prikaz teksta "Popust"
 * - getTxtDiscount() - Tekstualno polje za unos popusta
 * - getLblQuantity() - Labela za prikaz teksta "Količina"
 * - getTxtProductQuantity() - Tekstualno polje za unos količine
 * - getLblWatched() - Labela za prikaz teksta "Gledano"
 * - getCbWatched() - ComboBox za izbor opcije "Gledano"
 * - getBtnRemove() - Dugme za uklanjanje stavke rezervacije
 * - getBtnSave() - Dugme za čuvanje rezervacije
 */

     private void prepareForChangeDelete() {
      getTxtInvoiceId().setVisible(false);
      getLblRezervacijaId().setVisible(false);
      getLblNumberOfShow().setVisible(true);
      getTxtInvoiceNumber().setVisible(true);

      getCbClient().setVisible(true);
      getLblClient().setVisible(true);
      getBtnSearch().setVisible(true);
      
      getCbReservations().setVisible(true);
      getBtnChoose().setVisible(true);
      
      getScrol().setVisible(true);
      getTblRezervacija().setVisible(true);
      getBtnRemove().setVisible(false);
      
      getPanelPredstava().setVisible(false);
      getCbPredstava().setVisible(false);
      getLblShow().setVisible(false);
      getBtnAddProduct().setVisible(false);
      getLblDiscount().setVisible(false);
      getTxtDiscount().setVisible(false);
      getLblQuantity().setVisible(false);
      getTxtProductQuantity().setVisible(false);
      getLblWatched().setVisible(false);
      getCbWatched().setVisible(false);
      getBtnChange().setVisible(true);
      getBtnDelete().setVisible(true);
      getBtnSave().setVisible(false);
    }
     /**
 * Priprema vidljivost komponenti na korisničkom interfejsu za izmenu rezervacije.
 * Postavlja vidljivost određenih komponenti na true ili false u skladu sa postavkama.
 * Vidljive komponente:
 * - getLblNumberOfShow() - Labela za prikaz teksta "Broj predstave"
 * - getTxtInvoiceNumber() - Tekstualno polje za prikaz broja predstave
 * - getCbClient() - ComboBox za izbor klijenta
 * - getLblClient() - Labela za prikaz teksta "Klijent"
 * - getCbReservations() - ComboBox za izbor rezervacije
 * - getBtnChoose() - Dugme za izbor rezervacije
 * - getTblRezervacija() - Tabela za prikaz rezervacija
 * - getBtnRemove() - Dugme za uklanjanje stavke rezervacije
 * - getPanelPredstava() - Panel za prikaz predstave
 * - getCbPredstava() - ComboBox za izbor predstave
 * - getLblShow() - Labela za prikaz teksta "Predstava"
 * - getBtnAddProduct() - Dugme za dodavanje stavke rezervacije
 * - getLblDiscount() - Labela za prikaz teksta "Popust"
 * - getTxtDiscount() - Tekstualno polje za unos popusta
 * - getLblQuantity() - Labela za prikaz teksta "Količina"
 * - getTxtProductQuantity() - Tekstualno polje za unos količine
 * - getLblWatched() - Labela za prikaz teksta "Gledano"
 * - getCbWatched() - ComboBox za izbor opcije "Gledano"
 * - getBtnSave() - Dugme za čuvanje rezervacije
 *
 * Nevidljive komponente:
 * - getTxtInvoiceId() - Tekstualno polje za prikaz ID rezervacije
 * - getLblRezervacijaId() - Labela za prikaz teksta "ID rezervacije"
 * - getBtnSearch() - Dugme za pretragu rezervacija
 * - getBtnChange() - Dugme za izmenu rezervacije
 * - getBtnDelete() - Dugme za brisanje rezervacije
 */

     private void prepareChange() {
      getTxtInvoiceId().setVisible(false);
      getLblRezervacijaId().setVisible(false);
      getLblNumberOfShow().setVisible(true);
      getTxtInvoiceNumber().setVisible(true);

      getCbClient().setVisible(true);
      getLblClient().setVisible(true);
      getBtnSearch().setVisible(false);
      
      getCbReservations().setVisible(true);
      getCbReservations().setEnabled(false);
      getBtnChoose().setVisible(true);
      getBtnChoose().setEnabled(false);
      
      getTblRezervacija().setVisible(true);
      getBtnRemove().setVisible(true);
      
      getPanelPredstava().setVisible(true);
      getCbPredstava().setVisible(true);
      getLblShow().setVisible(true);
      getBtnAddProduct().setVisible(true);
      getLblDiscount().setVisible(true);
      getTxtDiscount().setVisible(true);
      getLblQuantity().setVisible(true);
      getTxtProductQuantity().setVisible(true);
      getLblWatched().setVisible(true);
      getCbWatched().setVisible(true);
      getBtnChange().setVisible(false);
      getBtnDelete().setVisible(false);   
      getBtnSave().setVisible(true);
     
    }

    
/**
 * Vraća listu predstava.
 *
 * @return Lista predstava.
 * @throws Exception U slučaju greške prilikom komunikacije.
 */
    private List<Predstava> getProducts() throws Exception {
        return Communication.getInstance().getAllProducts();
    }
   /**
 * Vraća listu klijenata.
 *
 * @return Lista klijenata.
 * @throws Exception U slučaju greške prilikom komunikacije.
 */ 
  private List<Klijent> getClients() throws Exception {
        return Communication.getInstance().getAllClients();
    }
  /**
 * Vraća listu rezervacija.
 *
 * @return Lista rezervacija.
 * @throws Exception U slučaju greške prilikom komunikacije.
 */
   private List<Rezervacija> getReservations() throws Exception {
        return Communication.getInstance().getAllReservations();
    }
   /**
 * Ažurira rezervaciju.
 *
 * @param invoice Rezervacija koja se ažurira.
 * @throws Exception U slučaju greške prilikom komunikacije.
 */
    private void updateInvoice(Rezervacija invoice) throws Exception {
        Communication.getInstance().updateRezervacija(invoice);
    }
    /**
 * Vraća listu stavki rezervacija.
 *
 * @return Lista stavki rezervacija.
 * @throws Exception U slučaju greške prilikom komunikacije.
 */
     private List<StavkaRezervacije> getStavke() throws Exception {
         return Communication.getInstance().getAllItemReservations();
    }
     /**
 * Vraća listu karata.
 *
 * @return Lista karata.
 * @throws Exception U slučaju greške prilikom komunikacije.
 */

      private List<Karta> getKarte() throws Exception {
         return Communication.getInstance().getAllTickets();
    }
  /**
 * Dodaje stavku rezervacije u listu "stare".
 *
 * @param s Stavka rezervacije koja se dodaje.
 */
             private void fillIt(StavkaRezervacije s){
         
       
          stare.add(s);
             
    
      }
/**
 * Ažurira stavku rezervacije.
 *
 * @param zaIzmenu Stavka rezervacije koja se ažurira.
 * @throws Exception U slučaju greške prilikom komunikacije.
 */
    private void updateStavka(StavkaRezervacije zaIzmenu) throws Exception {
        Communication.getInstance().updateRezervacija(zaIzmenu);
    }
    /**
 * Dodaje stavku rezervacije u listu.
 *
 * @param st Stavka rezervacije koja se dodaje.
 * @throws Exception U slučaju greške prilikom komunikacije.
 */
     private void addStavke(StavkaRezervacije st) throws Exception {
         Communication.getInstance().addStavke(st);
    }
/**
 * Briše stavku rezervacije iz liste.
 *
 * @param st Stavka rezervacije koja se briše.
 * @throws Exception U slučaju greške prilikom komunikacije.
 */
    private void deleteStavke(StavkaRezervacije st) throws Exception {
        Communication.getInstance().deleteStavka(st);
    }
/**
 * Briše kartu.
 *
 * @param k Karta koja se briše.
 * @throws Exception U slučaju greške prilikom komunikacije.
 */
    private void deleteKarta(Karta k) throws Exception {
        Communication.getInstance().deleteTicket(k);
    }
}
