/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import rs.ac.bg.fon.ps.communication.Communication;
import rs.ac.bg.fon.ps.communication.LocalStorage;
import rs.ac.bg.fon.ps.domain.Karta;
import rs.ac.bg.fon.ps.domain.Predstava;
import rs.ac.bg.fon.ps.domain.Rezervacija;
import rs.ac.bg.fon.ps.view.form.componenet.table.ShowsTableModel;
import rs.ac.bg.fon.ps.view.form.util.FormMode;


public class FrmViewTickets extends javax.swing.JDialog {

    /**
     * Creates new form FrmViewProducts
     * @param parent
     */
    private LocalStorage localStorage = LocalStorage.getInstance();
    public FrmViewTickets(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDetails = new javax.swing.JButton();
        lblShow = new javax.swing.JLabel();
        txtNameOfShow = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbTickets = new javax.swing.JComboBox<>();
        lblClient = new javax.swing.JLabel();
        txtNameOfClient = new javax.swing.JTextField();
        lblTicket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form for view tickets");

        btnDetails.setText("Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        lblShow.setText("Search by name of show:");

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblClient.setText("Search by name of client:");

        lblTicket.setText("TICKETS:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTicket)
                            .addGap(18, 18, 18)
                            .addComponent(cbTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNameOfClient, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblShow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNameOfShow, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnSearch)))
                .addGap(0, 61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShow)
                    .addComponent(txtNameOfShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClient)
                    .addComponent(txtNameOfClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnSearch)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTicket))
                .addGap(18, 18, 18)
                .addComponent(btnDetails)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO...
        if(getCbTickets().getSelectedIndex()!=-1){
            Karta k=(Karta) getCbTickets().getSelectedItem();
            localStorage.addItemsInHashMap("Karta",k);
            System.out.println(k);
            FrmKarta forma=new FrmKarta(null, rootPaneCheckingEnabled, FormMode.FORM_VIEW);
            forma.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"System can not load ticket, please set ticket","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
       
       getBtnDetails().setVisible(true);
       getCbTickets().setVisible(true);
       getLblTicket().setVisible(true);
       
         List<Karta> tickets;
         List<Karta> ticketsToShow=new ArrayList<>();
        try {
            tickets = Communication.getInstance().getAllTickets();
            for(Karta k:tickets){
                if(k.getRezervacijaId().getKlijentId().getIme().equalsIgnoreCase(getTxtNameOfClient().getText()) && k.getStavkaId().getPredstavaId().getNaziv().equalsIgnoreCase(getTxtNameOfShow().getText())){
                    ticketsToShow.add(k);
                }
            }
             getCbTickets().setModel(new DefaultComboBoxModel(ticketsToShow.toArray()));
            getCbTickets().setSelectedIndex(-1);
            getCbTickets().setVisible(true);
            
            if(ticketsToShow.isEmpty()){
                JOptionPane.showMessageDialog(this,"Nema karata sa unetim podacima","ERROR",JOptionPane.ERROR_MESSAGE);
                getCbTickets().setVisible(false);
            }
            else{
                     JOptionPane.showMessageDialog(this,"Sistem je nasao karte sa unetim podacima");
                getCbTickets().setModel(new DefaultComboBoxModel(ticketsToShow.toArray()));
            getCbTickets().setSelectedIndex(-1);
            getCbTickets().setVisible(true);
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "ERROR DETAILS", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<Object> cbTickets;
    private javax.swing.JLabel lblClient;
    private javax.swing.JLabel lblShow;
    private javax.swing.JLabel lblTicket;
    private javax.swing.JTextField txtNameOfClient;
    private javax.swing.JTextField txtNameOfShow;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnDetails() {
        return btnDetails;
    }
     public JButton getBtnSearch() {
        return btnSearch;
    }
      public JComboBox<Object> getCbTickets() {
        return cbTickets;
    }
    public JTextField getTxtNameOfShow() {
        return txtNameOfShow;
    }
    public JTextField getTxtNameOfClient() {
        return txtNameOfClient;
    }
     public JLabel getLblSearch() {
        return lblShow;
    }
      public JLabel getLblTicket() {
        return lblTicket;
    }

  

    public void getBtnDetailsAddActionListener(ActionListener actionListener) {
        btnDetails.addActionListener(actionListener);
    }
    
    private void prepareView() {
       getBtnDetails().setVisible(false);
       getCbTickets().setVisible(false);
       getLblTicket().setVisible(false);
        
    }

    
}
